services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: 74ccdd
      POSTGRES_PASSWORD: 74ccdd
      POSTGRES_DB: 74ccdd
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
